### ISSUE TITLE
Best solution for palindrome checker does 2x the amount of work necessary

### ISSUE THREAD

**Issue by ddalcino** [CoffeeBeforeArch/clever_code#1]
The final solution you present, isPalindromeBest(), can still be optimized.

This expression performs twice as many comparisons as are needed.

    equal(begin(s), end(s), rbegin(s));

You can skip half the comparisons by changing the end iterator:

    equal(begin(s), begin(s) + (s.size() / 2), rbegin(s));

**Comment by ddalcino** [comment]
I made a fork of this project on my github, using google benchmark, and I get this result:

```
--------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations
--------------------------------------------------------------------
BM_isPalindromeBad              10.4 ns         10.4 ns     68378295
BM_isPalindromeBetter1          31.9 ns         31.9 ns     22026551
BM_isPalindromeBetter2          44.1 ns         44.0 ns     15657873
BM_isPalindromeBest             19.9 ns         19.8 ns     35303968
BM_isPalindromeBestTimes2       10.3 ns         10.2 ns     68707719

Process finished with exit code 0

```

**Comment by CoffeeBeforeArch** [comment]
Thank you for catching that! I've updated the code to reflect this, and will be updating the posted video.
