### ISSUE TITLE
findOddBest17() using std::reduce

### ISSUE THREAD

**Issue by ddalcino** [CoffeeBeforeArch/clever_code#2]
I noticed in your commits for find_odd.cpp that you had intended to include an example using the std::reduce algorithm, but couldn't get it to compile. I was able to get it working on my system, like this:

    int findOddBest17(const vector<int> &v) {
      // Bit-wise XOR of all elements
      return reduce(std::execution::par, begin(v), end(v), 0, bit_xor<>());
    }

This code requires that you `#include <execution>`, and link to `tbb`. You might need to link to `pthread` as well since it parallelizes the code. I'm not sure because I've only tried to run it using Google Benchmark, and that uses pthread.

In case you wind up revisiting this in a video, please note that the size of your test vector makes a big difference here. For me, the std::reduce solution was slower than any of the others with fewer than 10,000 items, and it was a lot faster for vectors over 100,000 items. I think there's a lot of setup overhead involved in parallelizing the problem, and it's not worth doing for small n.

**Comment by CoffeeBeforeArch** [comment]
Yeah, I've used the parallel STL in C++ crash course, and even used reduce in that example ( https://github.com/CoffeeBeforeArch/cpp_crash_course/blob/master/optimizations/parallel_algorithms/parallel_algorithms.cpp ). The compilation problem was just local environment thing that I have fixed.

Being slow for a small number of elements makes sense if the cost of spawning threads and joining them can't be amortized across the actual work. I may run some tests and generate some plots to show this. My assumption was that this was already handled by TBB (I believe I read/heard somewhere that it had logic built in to disable parallelization if it wasn't a wise decision (same with vectorization). It'd be nice to show this could really be improved by vectorization, but I think only the Xeon Phi has the bitwise xor vector hardware.

I will probably do a separate video on the parallel STL. Part of the reason I didn't include it was that support only came around with GCC 9.1 and requires TBB, and it still isn't supported by Clang libc++ or Apple Clang (at least that's what the compiler support doc I follow says).
